### ISSUE TITLE
 Create a document describing our NPM registry things work

### ISSUE THREAD

**Issue by hargup** [felvin-search/docs#37]

**Comment by OrkoHunter** [comment]
## Notes on NPM orgs

There is a few NPM organizations that we own on NPM - https://www.npmjs.com

- [felvin](https://www.npmjs.com/settings/felvin/packages)
- [felvin-search](https://www.npmjs.com/settings/felvin-search/packages)
- [felvin-search-apps](https://www.npmjs.com/settings/felvin-search-apps/packages)

An npm package can be published independently without any association with any org e.g. `react`. But if there is an organization publishing multiple packages, it's better to namespace them under an org. e.g. `@types/react`, `@types/<etc.>`. Here, `types` is the name of the org and the whole `@types/<package>` is the name of the NPM package.

Now for the Felvin Open Source Instant Apps - it's better to group the open source apps under one org but keep the core under a separate org. So, the felvin-search-apps org is used for publishing those apps. Examples [1](https://github.com/felvin-search/instant-apps/blob/51b2e0bc43b192f4f6e1826e4de5e35c9a7e307e/apps/bouncy-ball/package.json#L2) [2](https://github.com/felvin-search/instant-apps/blob/51b2e0bc43b192f4f6e1826e4de5e35c9a7e307e/apps/capitals/package.json#L2).

But felvin-search namespace is used for core packages. Example [1](https://github.com/felvin-search/felvin.com/blob/80d9fc4252199c5b1d7e79e7dfece82f42a433a4/packages/core/package.json#L2) [2](https://github.com/felvin-search/felvin.com/blob/80d9fc4252199c5b1d7e79e7dfece82f42a433a4/packages/cli/package.json#L2).

The felvin org is unused as of now.

## Membership

@hargup you are an Owner of both felvin and felvin-search orgs. Once you accept the invitation on felvin-search-apps, I'll make you an owner of the org.

- [ ] TODO: @hargup to accept invite of felvin-search-apps org
- [ ] TODO: Make @hargup owner of felvin-search-apps org

We do not use teams on NPM, members are added on individual basis. And it's all free since the packages are public.

## Publishing

Both https://github.com/felvin-search/felvin.com and https://github.com/felvin-search/instant-apps has publishing enabled for its NPM packages (core and open source packages respectively).

There is an `NPM_TOKEN` environment variable stored in GitHub secrets which is used in the GitHub actions CI environment.

- [ ] TODO: @hargup - generate an NPM token of your account and update the secrets in both repositories. 1. https://github.com/felvin-search/felvin.com/settings/secrets/actions 2. https://github.com/felvin-search/instant-apps/settings/secrets/actions 3. Docs: https://docs.npmjs.com/creating-and-viewing-access-tokens

All the packages are published using [this release workflow](https://github.com/felvin-search/instant-apps/blob/master/.github/workflows/release.yml) which publishes them once every day, but can also be triggered manually from the Actions tab. https://github.com/felvin-search/instant-apps/actions/workflows/release.yml

## Side note about `PAT`

While we are at updating the secrets, I notice a `PAT` environment variable. I think this is a GitHub Personal Access Token.

@sahil-shubham do we really need it? GitHub actions automatically creates a `secrets.GITHUB_TOKEN` env variable which should be enough to do a checkout of the repository. Let us know if PAT has any other use-case and if we should keep it or remove it. If we're to keep it, we should ask @hargup to update with his own github token.

**Comment by sahil-shubham** [comment]
> Let us know if PAT has any other use-case and if we should keep it or remove it. If we're to keep it, we should ask @hargup to update with his own github token.

It's used so that the action can commit any changes from my place. We should replace it with Harsh's PAT as I would be losing the write access to private repositories soon.

**Comment by hargup** [comment]
@OrkoHunter thanks for the detailed instructions. I have:

- accepted invite to felvin-search-apps
- Updated NPM_TOKEN for the instant apps repository
- Updated NPM_TOKEN for the felvin.com repository

Please make me owner of `felvin-search-apps` org. BTW, I'm considering renaming the org `felvin-search-apps` with `felvin-community` org. Reason `felvin-search` and `felvin-search-apps` is kinda confusing. We can use `felvin-community` org for all community maintained open source projects sponsored by Felvin, it also explicitly acknowledges the involvement of the community.

How do you feel about the new proposed name?

**Comment by OrkoHunter** [comment]
All TODOs done here. Name rename sounds good to me as discussed over email. :)

**Comment by hargup** [comment]
@sahil-shubham can you take up renaming the NPM org from `felvin-search-apps` to `felvin-community`?

**Comment by hargup** [comment]
This ticket was done, thanks for the work @OrkoHunter

**Comment by sahil-shubham** [comment]
> can you take up renaming the NPM org from felvin-search-apps to felvin-community?

Would change it, cool.
